server:
  port: 8081
  servlet:
    context-path: /
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml

app:
  consistency:
    cluster.name: consistency
    rocketmq:
      host: 192.168.15.37:9876
    executor:
      core-pool-size: 5
      keep-alive-seconds: 1000
      max-pool-size: 10
      queue-capacity: 20
    binlog:
      participant:
        id: watcher
      zk.address: localhost:2181

logging:
  level:
    org.springframework: info
    com.syswin.temail: info


spring:
  profiles:
    active: usermail

---
spring:
  profiles: usermail
  datasource:
    url: jdbc:mysql://localhost:3306/temail_data_consistency?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: groupmail
  datasource:
    url: jdbc:mysql://192.168.15.108:3316/temail_usermailagent?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: app
    password: temail#app
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: topic
  datasource:
    url: jdbc:mysql://192.168.15.108:3316/temail_usermailagent?useSSL=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: app
    password: temail#app
    driver-class-name: com.mysql.jdbc.Driver

